### ISSUE TITLE
One comma too much in topic list

### ISSUE THREAD

**Issue by Countrycoin-de** [smainz/OpenDTU-MQTT-Telegraf-influxdb-integration#1]
Hi, this is my first attempt on Github,
Trying to adapt your great work to my influx V1.8.10
Think there is one comma too much at the end of this list.
I don't know at the moment if it matters.

`topics = [
    "$DTU_BASE_TOPIC/dtu/status",
    "$DTU_BASE_TOPIC/dtu/ip",
    "$DTU_BASE_TOPIC/dtu/hostname",
  ]`

also here
`topics = [
    "$DTU_BASE_TOPIC/+/device/+",
    "$DTU_BASE_TOPIC/+/name",
  ]`

and here
` topics = [
    "$DTU_BASE_TOPIC/+/status/+",
    "$DTU_BASE_TOPIC/+/0/temperature",
  ]`

**Comment by smainz** [comment]
Well spotted! This is not very consistent, but [TOML](https://toml.io/en/v1.0.0#array) allows trailing comma in an array. I will accept a PR.

To adapt to influxdb V1 you will have to change the output section, not the inputs (hopefully).

I will post the grafana dashboard soon, which will use flux as query language, but i do not test with influxdb V1.
