### ISSUE TITLE
just a thank you. no problem!

### ISSUE THREAD

**Issue by Banabas** [smainz/OpenDTU-MQTT-Telegraf-influxdb-integration#2]
Danke für die telegraf.config.
Hat mir sehr geholfen. 

Musste aber doch erstmal schauen wie was wo eingetragen werden muss aber es läuft.
Mit InfluxDB v1...
Vielleicht noch den Hinweis geben wo die Base Topic ist. OpenDTU Standard "solar" und  was man ändern muss.
Die Einträge mit $ am Anfang.
User und Passwort habe ich mit # auskommentiert.

Nochmals vielen Dank für deine config.

Grüße

**Comment by smainz** [comment]
Diese Woche gibt es noch ein update inkl. Grafana Dashboard und eine `docker-compose.yml` zum Starten (inkl. Doku).
Die Aufteilung in die `measurements` habe ich noch etwas geändert, da ich festgestellt habe, das  der erste Filter, den ich setze immer auf `channel_type` geht.
