### ISSUE TITLE
telegraf.weather.conf 

### ISSUE THREAD

**Issue by Banabas** [smainz/OpenDTU-MQTT-Telegraf-influxdb-integration#4]
Good day,
I have a small problem.
I have set up everything and it is running.
However, not in the container but on ProxmoxxLCX.
Only the weather bucket is still missing.
How do I get the Telegraf.Weather.config to work?
Do I have to start Telegraf a second time?
It would be great if you could help me.

Greetings
Sven

Guten Tag,
ich habe ein kleines Problem.
Habe alles eingerichtet und es läuft auch.
Allerdings nicht im Container sondern auf ProxmoxxLCX.
Nur der weather bucket fehlt noch.
Wie bekomme ich die Telegraf.Weather.config zu laufen?
Muss ich Telegraf ein zweites mal starten?
Wäre klasse wenn du mir helfen könntest.

Grüße
Sven

**Comment by Banabas** [comment]
Hab es hinbekommen.
hab sie nach "/etc/telegraf/telegraf.d" kopiert.
Jetzt läuft´s.

**Comment by smainz** [comment]
Schön, das es funktioniert hat. 
Prinzipiell gibt es drei Möglichkeiten:
- einen eigene Telegraf-Prozess mit eigener Konfigurationsdatei
- den Inhalt in die andere Datei kopieren (- output)
- sowie du es gemacht hast.
-
Da sollte ich mal die Konfiguration umbaue nund die Doku erweitern.

**Comment by Banabas** [comment]
Schreibe das jetzt mal einfach noch hier mit rein.
Könntest du nicht vielleicht noch die Monate mit anzeigen zu lassen.
Also ein Balkendiagramm von den Monaten.
Das hätte doch noch wunderbar Platz da drinnen.

**Comment by smainz** [comment]
Was meinst Du mit Monate anzeigen lassen? Sicherlich nicht die Monatsnamen.
Also welchen Wert über die Monate?

**Comment by Banabas** [comment]
Nee.
Die Erträge pro Monat.
So das man ein Monatsverlauf hat.
Ist das möglich mit Grafana das da die ganzen Tage des Monats zusammen gerechnet werden?

**Comment by smainz** [comment]
Also Ertrag pro Monat,  über einen Zeitraum von z.B. 1 Jahr?
Das sollte gehen. Rechnen tut nicht grafana, sondern influxdb, grafana zeigt das Ergebnis nur an

**Comment by Banabas** [comment]
Ja genau. So meinte ich das.
Wäre ja klasse wenn das möglich ist.
Dachte aber das Grafana sowas auch kann mit "math".
Aber da kenne ich mich nicht mit aus.
Baust du dir die Fenster dann direkt in InfluxDB v2 Webinterface?

**Comment by smainz** [comment]
Ich tippe den Code einfach in Grafana in die Query-Fenster ein.
Beim Ausführen dir die Query an influxdb geschickt und von dort kommt dann das Ergebnis zurück.

Im Prinzip ist klar, wie die Query aussehen muss, aber nachdem ich hier auf den vollen Datenbestand gehe, muss ich das noch optimieren, sonst läuft das ewig.

**Comment by smainz** [comment]
So was?

![image](https://github.com/smainz/OpenDTU-MQTT-Telegraf-influxdb-integration/assets/15262922/8e42680a-e4fb-4987-9eae-7410ff679f60)

Ich bin jetzt nicht das Grafikgenie insofern sind Anregungen gerne gesehen.

**Comment by Banabas** [comment]
Ja sieht schon nicht schlecht aus.
Die 3 Monate stehen da jetzt so weil nur Daten aus 3 Monaten da sind schätze ich mal.
Also um so mehr Daten aus den Monaten um so mehr Balken?
